name: Node.js CI/CD to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REPO: node-api-repo
  SERVICE: node-api-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Force Dependency Resolution
        run: |
          # Force update vulnerable packages
          npm install cross-spawn@7.0.6 --save-exact
          npm install brace-expansion@2.0.2 --save-exact
          
          # Update lockfile
          npm install
          
          # Verify updates
          npm list cross-spawn brace-expansion

      - name: Run Linter
        run: npm run lint

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://${{ env.REGION }}-docker.pkg.dev

      - name: Set image name
        id: set-image
        run: |
          echo "IMAGE_NAME=${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO }}/node-api:${{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_NAME_LATEST=${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO }}/node-api:latest" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build --no-cache -t ${{ env.IMAGE_NAME }} .

      - name: Verify Dependencies
        run: |
          # Check for vulnerable packages
          docker run --rm ${{ env.IMAGE_NAME }} npm list cross-spawn brace-expansion
          
          # Check installed versions
          docker run --rm ${{ env.IMAGE_NAME }} npm list cross-spawn --parseable | grep -oE '[^/]+$' | grep -q '7.0.6' || exit 1
          docker run --rm ${{ env.IMAGE_NAME }} npm list brace-expansion --parseable | grep -oE '[^/]+$' | grep -q '2.0.2' || exit 1

      - name: Push to Artifact Registry
        run: |
          docker push ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_NAME_LATEST }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.IMAGE_NAME }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --min-instances=0 \
            --max-instances=1 \
            --update-env-vars PORT=8080